<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <RazorRuntimeCompilation>false</RazorRuntimeCompilation>
    <!-- Test value for Lombiq.Hosting.BuildVersionDisplay. Intentionally different than the value in its props file. -->
    <BuildVersionDisplay_BuildUrl>
      https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/456
    </BuildVersionDisplay_BuildUrl>
    <MarkdownAnalysis>solution</MarkdownAnalysis>
    <ExecDotnetPostcleanCommand>false</ExecDotnetPostcleanCommand>
    <ExecDotnetPrebuildCommand>false</ExecDotnetPrebuildCommand>
    <OrchardCoreVersion>3.0.0-preview-18983</OrchardCoreVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
    <None Remove="node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.AuditTrailExtensions" />
    <PackageReference Include="Lombiq.BaseTheme.Core" />
    <PackageReference Include="Lombiq.BaseTheme.Native" />
    <PackageReference Include="Lombiq.BaseTheme.Native.Samples" />
    <PackageReference Include="Lombiq.ChartJs" />
    <PackageReference Include="Lombiq.ChartJs.Samples" />
    <PackageReference Include="Lombiq.ContentEditors" />
    <PackageReference Include="Lombiq.ContentEditors.Samples" />
    <PackageReference Include="Lombiq.DataTables" />
    <PackageReference Include="Lombiq.DataTables.Samples" />
    <PackageReference Include="Lombiq.EmailClient" />
    <PackageReference Include="Lombiq.EmailClient.Samples" />
    <PackageReference Include="Lombiq.HelpfulExtensions" />
    <PackageReference Include="Lombiq.HelpfulLibraries" />
    <PackageReference Include="Lombiq.Hosting.Azure.ApplicationInsights" />
    <PackageReference Include="Lombiq.Hosting.BuildVersionDisplay" />
    <PackageReference Include="Lombiq.Hosting.MediaTheme" />
    <PackageReference Include="Lombiq.Hosting.MediaTheme.Tests.Theme" />
    <PackageReference Include="Lombiq.Hosting.MediaTheme.Bridge" />
    <PackageReference Include="Lombiq.Hosting.MediaTheme.Targets" />
    <PackageReference Include="Lombiq.Hosting.Tenants.Admin.Login" />
    <PackageReference Include="Lombiq.Hosting.Tenants.EnvironmentRobots" />
    <PackageReference Include="Lombiq.Hosting.Tenants.FeaturesGuard" />
    <PackageReference Include="Lombiq.Hosting.Tenants.IdleTenantManagement" />
    <PackageReference Include="Lombiq.Hosting.Tenants.Maintenance" />
    <PackageReference Include="Lombiq.Hosting.Tenants.Management" />
    <PackageReference Include="Lombiq.Hosting.Tenants.MediaStorageManagement" />
    <PackageReference Include="Lombiq.Hosting.Tenants.EmailQuotaManagement" />
    <PackageReference Include="Lombiq.Marketing" />
    <PackageReference Include="Lombiq.Marketing.Pirsch" />
    <PackageReference Include="Lombiq.Marketing.UrlShortener" />
    <PackageReference Include="Lombiq.JsonEditor" />
    <PackageReference Include="Lombiq.LoginAsAnybody" />
    <PackageReference Include="Lombiq.Privacy" />
    <PackageReference Include="Lombiq.Privacy.Samples" />
    <PackageReference Include="Lombiq.SetupExtensions" />
    <PackageReference Include="Lombiq.Tests.UI.AppExtensions" />
    <PackageReference Include="Lombiq.Tests.UI.Shortcuts" />
    <PackageReference Include="Lombiq.UIKit" />
    <PackageReference Include="Lombiq.UIKit.Widgets" />
    <PackageReference Include="Lombiq.UIKit.Widgets.Tests.UI" />
    <PackageReference Include="Lombiq.VueJs.Resources" />
    <PackageReference Include="Lombiq.Walkthroughs" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Condition="'$(RazorRuntimeCompilation)' == 'true'" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Logging.NLog" />
    <PackageReference Include="OrchardCore.Application.Cms.Targets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Lombiq.OSOCE.NuGet.TestModule\Lombiq.OSOCE.NuGet.TestModule.csproj" />
    <ProjectReference Include="..\Themes\Lombiq.OSOCE.NuGet.TestTheme\Lombiq.OSOCE.NuGet.TestTheme.csproj" />
  </ItemGroup>

</Project>
