# Schema with docs on the properties: https://coderabbit.ai/integrations/coderabbit-overrides.v2.json. This only
# includes overrides for defaults.

early_access: false
reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
