# Schema with docs on the properties: https://coderabbit.ai/integrations/coderabbit-overrides.v2.json. This only
# includes overrides for defaults and mandatory elements.

early_access: false
reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  # Usually just noise, enable for debugging.
  review_status: false
  # Maybe true?
  collapse_walkthrough: true
  auto_review:
    enabled: true
chat:
  auto_reply: true
