<Project Sdk="Lombiq.MSBuild.OrchardCore.Tests.Sdk/2.0.3-alpha.0.osoe-1286">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.HelpfulLibraries" />
    <PackageReference Include="Lombiq.EInvoiceValidator" />
    <PackageReference Include="Lombiq.EInvoiceValidator.Sample" />
  </ItemGroup>
</Project>
