<Project Sdk="Lombiq.MSBuild.OrchardCore.Tests.Sdk/2.1.0">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.HelpfulLibraries" />
    <PackageReference Include="Lombiq.EInvoiceValidator" />
    <PackageReference Include="Lombiq.EInvoiceValidator.Sample" />
  </ItemGroup>
</Project>
