<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="*.htmlvalidate.json" />
    <Content Include=".htmlvalidate.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="*.htmlvalidate.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../test/Lombiq.OSOCE.Tests.UI/*.htmlvalidate.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" />
    <PackageReference Include="Lombiq.BaseTheme.Tests.UI" />
    <PackageReference Include="Lombiq.ChartJs.Tests.UI" />
    <PackageReference Include="Lombiq.ContentEditors.Tests.UI" />
    <PackageReference Include="Lombiq.DataTables.Tests.UI" />
    <PackageReference Include="Lombiq.EmailClient.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.Azure.ApplicationInsights.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.BuildVersionDisplay.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.MediaTheme.Bridge.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.MediaTheme.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.Tenants.EnvironmentRobots.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.Tenants.FeaturesGuard.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.Tenants.IdleTenantManagement.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.Tenants.MediaStorageManagement.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.Tenants.EmailQuotaManagement.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.Tenants.Maintenance.Tests.UI" />
    <PackageReference Include="Lombiq.Hosting.Tenants.Management.Tests.UI" />
    <PackageReference Include="Lombiq.JsonEditor.Tests.UI" />
    <PackageReference Include="Lombiq.LoginAsAnybody.Tests.UI" />
    <PackageReference Include="Lombiq.Marketing.Tests.UI" />
    <PackageReference Include="Lombiq.OrchardCoreApiClient.Tests.UI" />
    <PackageReference Include="Lombiq.Privacy.Tests.UI" />
    <PackageReference Include="Lombiq.HelpfulExtensions.Tests.UI" />
    <PackageReference Include="Lombiq.Tests.UI" />
    <PackageReference Include="Lombiq.UIKit.Widgets.Tests.UI" />
    <PackageReference Include="Lombiq.Walkthroughs.Tests.UI" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lombiq.OSOCE.NuGet.Web\Lombiq.OSOCE.NuGet.Web.csproj" />
  </ItemGroup>

</Project>
