using Lombiq.Tests.UI.Extensions;
using Lombiq.Tests.UI.SqlQueryMonitoring.Extensions;
using Shouldly;
using System.Threading.Tasks;
using Xunit;

namespace Lombiq.OSOCE.Tests.UI.Tests.SqlMonitoringTests;

// Here we'll see how to detect potentially inefficient SQL query patterns during UI tests. This can help surface
// classic SELECT N+1 issues (the same SQL command running many times with different parameters), unintentional cache
// misses (the same query with the same parameters running repeatedly), and large result sets that should have been
// filtered.
public class SqlQueryMonitoringBasicsTests : Lombiq.Tests.UI.Samples.UITestBase
{
    public SqlQueryMonitoringBasicsTests(ITestOutputHelper testOutputHelper)
        : base(testOutputHelper)
    {
    }

    [Fact]
    public Task SqlQueryMonitoringShouldCatchDuplicatesAndLargeResults() =>
        ExecuteTestAfterSetupAsync(
            async context =>
            {
                // The test loads the home page by default. We'll assert on the SQL queries generated by that request.
                await context.AssertSqlQueryMonitoringAsync();

                // Navigate to another page and run a custom assertion.
                await context.GoToRelativeUrlAsync("/categories/travel");

                // Custom assertion example: here we just check that at least one SQL command was captured.
                await context.AssertSqlQueryMonitoringAsync(summary =>
                {
                    summary.Executions.ShouldNotBeEmpty("SQL query monitoring should capture at least one command.");

                    // You can apply your own logic to the summary, e.g. allowlist a specific command or collect stats
                    // for reporting.
                    return Task.CompletedTask;
                });
            },
            configuration =>
            {
                // Set thresholds high enough for this sample to pass. Lower these values in your tests to catch
                // potential issues in the app under test.
                // Same command text repeated with any parameters (useful for spotting SELECT N+1 patterns).
                configuration.SqlQueryMonitoringConfiguration.DuplicateCommandThreshold = 30;

                // Same command text repeated with the same parameter values (useful for spotting missing caching).
                configuration.SqlQueryMonitoringConfiguration.DuplicateCommandWithParametersThreshold = 15;

                // Commands returning more rows than expected (useful for spotting missing SQL filtering).
                configuration.SqlQueryMonitoringConfiguration.ResultSetRowCountThreshold = 200;

                return Task.CompletedTask;
            });
}

// NEXT STATION: Head over to Tests/SqlQueryMonitoringDisableCollectionTests.cs.
