<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*;node_modules\**;Tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="node_modules\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="package.json" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.Npm.Targets" />
    <PackageReference Include="OrchardCore.Theme.Targets" />
    <PackageReference Include="OrchardCore.ContentManagement" />
    <PackageReference Include="OrchardCore.DisplayManagement" />
    <PackageReference Include="OrchardCore.ResourceManagement" />
  </ItemGroup>

</Project>
