<Project>
  <PropertyGroup>
    <NuGetTestbed>true</NuGetTestbed>
    <UseGlobalNodeJsExtensionsNpmPackage>true</UseGlobalNodeJsExtensionsNpmPackage>
    <NodeJsExtensionsNpmPackageSourcePath>$(MSBuildThisFileDirectory)node_modules/.nx</NodeJsExtensionsNpmPackageSourcePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.Analyzers.OrchardCore" Version="5.1.1-alpha.2.osoe-984"><!-- #spell-check-ignore-line -->
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
