<Project>
  <PropertyGroup>
    <NuGetTestbed>true</NuGetTestbed>
    <UseGlobalNodeJsExtensionsNpmPackage>true</UseGlobalNodeJsExtensionsNpmPackage>
    <NodeJsExtensionsNpmPackageSourcePath>$(MSBuildThisFileDirectory)node_modules/.nx</NodeJsExtensionsNpmPackageSourcePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.Analyzers.OrchardCore">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Suppresses vulnerabilities in 'SixLabors.ImageSharp' version 3.1.12, until the Orchard Core upgrade to v4 is
  released that drops ImageSharp. -->
  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-gwg2-r3hj-4w44" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-j3p4-wp97-rph4" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-j9gm-c75j-xc9q" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-jjfr-hcj7-qf5w" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-wmxv-xphr-5c9g" />
  </ItemGroup>
</Project>
