<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <OrchardCoreVersion>3.0.1</OrchardCoreVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Lombiq.Analyzers.OrchardCore" Version="5.2.1-alpha.5.osoe-925" />
    <PackageVersion Include="Lombiq.AuditTrailExtensions" Version="8.0.1-alpha.3.osoe-925" />
    <PackageVersion Include="Lombiq.BaseTheme.Core" Version="11.0.1-alpha.6.osoe-925" />
    <PackageVersion Include="Lombiq.BaseTheme.Native" Version="11.0.1-alpha.6.osoe-925" />
    <PackageVersion Include="Lombiq.BaseTheme.Native.Samples" Version="11.0.1-alpha.6.osoe-925" />
    <PackageVersion Include="Lombiq.BaseTheme.Tests.UI" Version="11.0.1-alpha.6.osoe-925" />
    <PackageVersion Include="Lombiq.ChartJs" Version="9.0.1-alpha.8.osoe-925" />
    <PackageVersion Include="Lombiq.ChartJs.Samples" Version="9.0.1-alpha.8.osoe-925" />
    <PackageVersion Include="Lombiq.ChartJs.Tests.UI" Version="9.0.1-alpha.8.osoe-925" />
    <PackageVersion Include="Lombiq.ContentEditors" Version="6.0.0-alpha.9.osoe-925" />
    <PackageVersion Include="Lombiq.ContentEditors.Samples" Version="6.0.0-alpha.9.osoe-925" />
    <PackageVersion Include="Lombiq.ContentEditors.Tests.UI" Version="6.0.0-alpha.9.osoe-925" />
    <PackageVersion Include="Lombiq.DataTables" Version="10.0.2-alpha.17.osoe-925" />
    <PackageVersion Include="Lombiq.DataTables.Samples" Version="10.0.2-alpha.17.osoe-925" />
    <PackageVersion Include="Lombiq.DataTables.Tests.UI" Version="10.0.2-alpha.17.osoe-925" />
    <PackageVersion Include="Lombiq.EInvoiceValidator" Version="1.0.1-alpha.6.osoe-925" />
    <PackageVersion Include="Lombiq.EInvoiceValidator.Sample" Version="1.0.1-alpha.6.osoe-925" />
    <PackageVersion Include="Lombiq.EmailClient" Version="1.0.0-alpha.12.osoe-925" />
    <PackageVersion Include="Lombiq.EmailClient.Samples" Version="1.0.0-alpha.12.osoe-925" />
    <PackageVersion Include="Lombiq.EmailClient.Tests.UI" Version="1.0.0-alpha.12.osoe-925" />
    <PackageVersion Include="Lombiq.HelpfulExtensions" Version="11.1.1-alpha.11.osoe-925" />
    <PackageVersion Include="Lombiq.HelpfulExtensions.Tests.UI" Version="11.1.1-alpha.11.osoe-925" />
    <PackageVersion Include="Lombiq.HelpfulLibraries" Version="12.6.1-alpha.10.osoe-925" />
    <PackageVersion Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.6.1-alpha.10.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Azure.ApplicationInsights" Version="10.0.1-alpha.4.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Azure.ApplicationInsights.Tests.UI" Version="10.0.1-alpha.4.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.BuildVersionDisplay" Version="7.0.1-alpha.6.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.BuildVersionDisplay.Tests.UI" Version="7.0.1-alpha.6.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.MediaTheme" Version="8.0.1-alpha.13.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.MediaTheme.Bridge" Version="8.0.1-alpha.13.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.MediaTheme.Bridge.Tests.UI" Version="8.0.1-alpha.13.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.MediaTheme.Targets" Version="8.0.1-alpha.13.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.MediaTheme.Tests.Theme" Version="8.0.1-alpha.13.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.MediaTheme.Tests.UI" Version="8.0.1-alpha.13.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.Admin.Login" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.EmailQuotaManagement" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.EmailQuotaManagement.Tests.UI" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.EnvironmentRobots" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.EnvironmentRobots.Tests.UI" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.FeaturesGuard" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.FeaturesGuard.Tests.UI" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.IdleTenantManagement" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.IdleTenantManagement.Tests.UI" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.Maintenance" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.Maintenance.Tests.UI" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.Management" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.Management.Tests.UI" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.MediaStorageManagement" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.Hosting.Tenants.MediaStorageManagement.Tests.UI" Version="9.0.1-alpha.24.osoe-925" />
    <PackageVersion Include="Lombiq.JsonEditor" Version="9.0.2-alpha.7.osoe-925" />
    <PackageVersion Include="Lombiq.JsonEditor.Tests.UI" Version="9.0.2-alpha.7.osoe-925" />
    <PackageVersion Include="Lombiq.LoginAsAnybody" Version="5.0.1-alpha.4.osoe-925" />
    <PackageVersion Include="Lombiq.LoginAsAnybody.Tests.UI" Version="5.0.1-alpha.4.osoe-925" />
    <PackageVersion Include="Lombiq.Marketing" Version="0.0.1-alpha.4.osoe-925" />
    <PackageVersion Include="Lombiq.Marketing.Pirsch" Version="0.0.1-alpha.4.osoe-925" />
    <PackageVersion Include="Lombiq.Marketing.UrlShortener" Version="0.0.1-alpha.4.osoe-925" />
    <PackageVersion Include="Lombiq.Marketing.Tests.UI" Version="0.0.1-alpha.4.osoe-925" />
    <PackageVersion Include="Lombiq.Npm.Targets" Version="1.5.3-alpha.1.osoe-925" />
    <PackageVersion Include="Lombiq.OrchardCoreApiClient.Tests.UI" Version="7.0.1-alpha.8.osoe-925" />
    <PackageVersion Include="Lombiq.Privacy" Version="10.0.1-alpha.10.osoe-925" />
    <PackageVersion Include="Lombiq.Privacy.Samples" Version="10.0.1-alpha.10.osoe-925" />
    <PackageVersion Include="Lombiq.Privacy.Tests.UI" Version="10.0.1-alpha.10.osoe-925" />
    <PackageVersion Include="Lombiq.SetupExtensions" Version="7.0.1-alpha.1.osoe-925" />
    <PackageVersion Include="Lombiq.Tests" Version="5.0.1-alpha.3.osoe-925" />
    <PackageVersion Include="Lombiq.Tests.UI" Version="14.2.2-alpha.20.osoe-925" />
    <PackageVersion Include="Lombiq.Tests.UI.AdminTheme" Version="14.2.2-alpha.20.osoe-925" />
    <PackageVersion Include="Lombiq.Tests.UI.AppExtensions" Version="14.2.2-alpha.20.osoe-925" />
    <PackageVersion Include="Lombiq.Tests.UI.Shortcuts" Version="14.2.2-alpha.20.osoe-925" />
    <PackageVersion Include="Lombiq.UIKit" Version="10.0.1-alpha.10.osoe-925" />
    <PackageVersion Include="Lombiq.UIKit.Widgets" Version="10.0.1-alpha.10.osoe-925" />
    <PackageVersion Include="Lombiq.UIKit.Widgets.Tests.UI" Version="10.0.1-alpha.10.osoe-925" />
    <PackageVersion Include="Lombiq.VueJs.Resources" Version="9.0.2-alpha.7.osoe-925" />
    <PackageVersion Include="Lombiq.Walkthroughs" Version="3.0.1-alpha.28.osoe-925" />
    <PackageVersion Include="Lombiq.Walkthroughs.Tests.UI" Version="3.0.1-alpha.28.osoe-925" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.9" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageVersion Include="OrchardCore.Application.Cms.Targets" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.ContentManagement" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.ContentTypes.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.DisplayManagement" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Logging.NLog" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Module.Targets" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.ResourceManagement" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="OrchardCore.Theme.Targets" Version="$(OrchardCoreVersion)" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="11.0.0-preview.5.26302.115" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>