<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18973" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="3.0.0-preview-18973" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="3.0.0-preview-18973" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.0-preview-18973" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.csproj" />
    <ProjectReference Include="..\Lombiq.UIKit\Lombiq.UIKit\Lombiq.UIKit.csproj" />
  </ItemGroup>

</Project>
