name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  asset-lint:
    name: Lint Assets
    uses: Lombiq/GitHub-Actions/.github/workflows/asset-lint.yml@issue/OSOE-1220
