name: Build and Test Windows

# Windows builds are only run on-demand, to be run once before merging a PR, and for pushes to dev. This is because
# Windows builds are much slower and more expensive than Ubuntu ones, and them catching issues that aren't surfaced
# under Ubuntu is rare (but does happen). So, not running them for every push of every PR.
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
  pull_request_review:
    types: [submitted]

jobs:
  build-and-test-larger-runners0:
    name: 0 Build and Test Windows - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      parent-job-name: root-solution-larger-runners0
      machine-types: '["warp-windows-latest-x64-8x"]'
      timeout-minutes: 50
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 720000
      build-verbosity: minimal
      test-filter: FullyQualifiedName!~SecurityScanningTests&FullyQualifiedName!~BehaviorElasticsearchTests
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'

  build-and-test-larger-runners1:
    name: 1 Build and Test Windows - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      parent-job-name: root-solution-larger-runners1
      machine-types: '["warp-windows-latest-x64-8x"]'
      timeout-minutes: 50
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 720000
      build-verbosity: minimal
      test-filter: FullyQualifiedName!~SecurityScanningTests&FullyQualifiedName!~BehaviorElasticsearchTests
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'

  build-and-test-larger-runners2:
    name: 2 Build and Test Windows - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      parent-job-name: root-solution-larger-runners2
      machine-types: '["warp-windows-latest-x64-8x"]'
      timeout-minutes: 50
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 720000
      build-verbosity: minimal
      test-filter: FullyQualifiedName!~SecurityScanningTests&FullyQualifiedName!~BehaviorElasticsearchTests
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'

  build-and-test-larger-runners3:
    name: 3 Build and Test Windows - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      parent-job-name: root-solution-larger-runners3
      machine-types: '["warp-windows-latest-x64-8x"]'
      timeout-minutes: 50
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 720000
      build-verbosity: minimal
      test-filter: FullyQualifiedName!~SecurityScanningTests&FullyQualifiedName!~BehaviorElasticsearchTests
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'

  build-and-test-larger-runners4:
    name: 4 Build and Test Windows - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      parent-job-name: root-solution-larger-runners4
      machine-types: '["warp-windows-latest-x64-8x"]'
      timeout-minutes: 50
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 720000
      build-verbosity: minimal
      test-filter: FullyQualifiedName!~SecurityScanningTests&FullyQualifiedName!~BehaviorElasticsearchTests
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'
