name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test-larger-runners0:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners) 0
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-1131
    with:
      parent-job-name: root-solution-larger-runners0
      machine-types: '["warp-ubuntu-2404-x64-4x"]'
      timeout-minutes: 30
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      set-up-elasticsearch: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 600000
      build-enable-nuget-caching: 'true'
      build-enable-npm-caching: 'true'
      # This way, we can see Node.js build issues in the build log.
      build-verbosity: minimal
      ui-test-retry-interval-seconds: '60'
      build-enable-code-analysis: 'false'
      verify-dotnet-consolidation: false
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'
      test-filter: FullyQualifiedName~TestSeleniumPerformance

  build-and-test-larger-runners1:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners) 1
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-1131
    with:
      parent-job-name: root-solution-larger-runners1
      machine-types: '["warp-ubuntu-2404-x64-4x"]'
      timeout-minutes: 30
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      set-up-elasticsearch: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 600000
      build-enable-nuget-caching: 'true'
      build-enable-npm-caching: 'true'
      # This way, we can see Node.js build issues in the build log.
      build-verbosity: minimal
      ui-test-retry-interval-seconds: '60'
      build-enable-code-analysis: 'false'
      verify-dotnet-consolidation: false
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'
      test-filter: FullyQualifiedName~TestSeleniumPerformance

  build-and-test-larger-runners2:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners) 2
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-1131
    with:
      parent-job-name: root-solution-larger-runners2
      machine-types: '["warp-ubuntu-2404-x64-4x"]'
      timeout-minutes: 30
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      set-up-elasticsearch: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 600000
      build-enable-nuget-caching: 'true'
      build-enable-npm-caching: 'true'
      # This way, we can see Node.js build issues in the build log.
      build-verbosity: minimal
      ui-test-retry-interval-seconds: '60'
      build-enable-code-analysis: 'false'
      verify-dotnet-consolidation: false
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'
      test-filter: FullyQualifiedName~TestSeleniumPerformance

  build-and-test-larger-runners3:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners) 3
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-1131
    with:
      parent-job-name: root-solution-larger-runners3
      machine-types: '["warp-ubuntu-2404-x64-4x"]'
      timeout-minutes: 30
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      set-up-elasticsearch: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 600000
      build-enable-nuget-caching: 'true'
      build-enable-npm-caching: 'true'
      # This way, we can see Node.js build issues in the build log.
      build-verbosity: minimal
      ui-test-retry-interval-seconds: '60'
      build-enable-code-analysis: 'false'
      verify-dotnet-consolidation: false
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'
      test-filter: FullyQualifiedName~TestSeleniumPerformance

  build-and-test-larger-runners4:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners) 4
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-1131
    with:
      parent-job-name: root-solution-larger-runners4
      machine-types: '["warp-ubuntu-2404-x64-4x"]'
      timeout-minutes: 30
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      set-up-elasticsearch: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 600000
      build-enable-nuget-caching: 'true'
      build-enable-npm-caching: 'true'
      # This way, we can see Node.js build issues in the build log.
      build-verbosity: minimal
      ui-test-retry-interval-seconds: '60'
      build-enable-code-analysis: 'false'
      verify-dotnet-consolidation: false
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'
      test-filter: FullyQualifiedName~TestSeleniumPerformance

  build-and-test-larger-runners5:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners) 5
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-1131
    with:
      parent-job-name: root-solution-larger-runners5
      machine-types: '["warp-ubuntu-2404-x64-4x"]'
      timeout-minutes: 30
      set-up-sql-server: 'true'
      set-up-azurite: 'true'
      set-up-elasticsearch: 'true'
      build-create-binary-log: 'true'
      blame-hang-timeout: 600000
      build-enable-nuget-caching: 'true'
      build-enable-npm-caching: 'true'
      # This way, we can see Node.js build issues in the build log.
      build-verbosity: minimal
      ui-test-retry-interval-seconds: '60'
      build-enable-code-analysis: 'false'
      verify-dotnet-consolidation: false
      cancel-in-progress-for-this-pr: 'false'
      cancel-workflow-on-failure: 'false'
      test-filter: FullyQualifiedName~TestSeleniumPerformance
